config/routes.rb
Rails.application.routes.draw do
  resources :homework_submissions
  resources :homework_assignments
  resources :homework_assignments
  resources :homeworks
  get 'homeworks/index'

  root 'homeworks#index'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create', as: 'session'
  match 'logout', to: 'sessions#destroy', as: 'logout', via: [:get, :delete]

    get 'assignments' => 'homework_assignments#index'
    get 'submit/:id' => 'homework_submissions#new'
    get 'user/:user_id/homework/:homework_id' => 'homework_submissions#submissionsByUserForHomework'
    get 'homework/:homework_id' => 'homework_submissions#viewLatestForAssignment'

end

app/models/homework_assignment.rb
class HomeworkAssignment < ActiveRecord::Base
	belongs_to :user

	has_many :homework_submissions
	belongs_to :homework
end

app/controllers/homework_assignments_controller.rb
class HomeworkAssignmentsController < ApplicationController
  before_action :set_homework_assignment, only: [:show, :edit, :update, :destroy]

  # GET /homework_assignments
  # GET /homework_assignments.json
  def index
    @homework_assignments = HomeworkAssignment.all
  end

  # GET /homework_assignments/1
  # GET /homework_assignments/1.json
  def show
  end

  # GET /homework_assignments/new
  def new
    @homework_assignment = HomeworkAssignment.new
  end

  # GET /homework_assignments/1/edit
  def edit
  end

  # POST /homework_assignments
  # POST /homework_assignments.json
  def create
    @homework_assignment = HomeworkAssignment.new(homework_assignment_params)

    respond_to do |format|
      if @homework_assignment.save
        format.html { redirect_to @homework_assignment, notice: 'Homework assignment was successfully created.' }
        format.json { render :show, status: :created, location: @homework_assignment }
      else
        format.html { render :new }
        format.json { render json: @homework_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homework_assignments/1
  # PATCH/PUT /homework_assignments/1.json
  def update
    respond_to do |format|
      if @homework_assignment.update(homework_assignment_params)
        format.html { redirect_to @homework_assignment, notice: 'Homework assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @homework_assignment }
      else
        format.html { render :edit }
        format.json { render json: @homework_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homework_assignments/1
  # DELETE /homework_assignments/1.json
  def destroy
    @homework_assignment.destroy
    respond_to do |format|
      format.html { redirect_to homework_assignments_url, notice: 'Homework assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homework_assignment
      @homework_assignment = HomeworkAssignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homework_assignment_params
      params[:homework_assignment]
    end
end

app/helpers/homework_assignments_helper.rb
module HomeworkAssignmentsHelper
end

app/views/homework_assignments/_form.html.erb
<%= form_for(@homework_assignment) do |f| %>
  <% if @homework_assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homework_assignment.errors.count, "error") %> prohibited this homework_assignment from being saved:</h2>

      <ul>
      <% @homework_assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homework_assignments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Homework Assignments</h1>

<table>
  <thead>
    <tr>
      <th>Homework id</th>
      <th>User id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homework_assignments.each do |homework_assignment| %>
      <tr>
        <td><%= homework_assignment.homework %></td>
        <td><%= homework_assignment.user_id %></td>

        <td><%= link_to 'Show', homework_assignment %></td>
        <td><%= link_to 'Edit', edit_homework_assignment_path(homework_assignment) %></td>
        <td><%= link_to 'Destroy', homework_assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homework assignment', new_homework_assignment_path %>