config/routes.rb
Rails.application.routes.draw do
  resources :homework_submissions
  resources :homework_assignments
  resources :homework_assignments
  resources :homeworks
  get 'homeworks/index'

  root 'homeworks#index'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create', as: 'session'
  match 'logout', to: 'sessions#destroy', as: 'logout', via: [:get, :delete]

    get 'assignments' => 'homework_assignments#index'
    get 'submit/:id' => 'homework_submissions#new'
    get 'user/:user_id/homework/:homework_id' => 'homework_submissions#submissionsByUserForHomework'
    get 'homework/:homework_id' => 'homework_submissions#viewLatestForAssignment'

end

app/models/homework_submission.rb
class HomeworkSubmission < ActiveRecord::Base
	belongs_to :homework_assignment

end

app/controllers/homework_submissions_controller.rb
class HomeworkSubmissionsController < ApplicationController
  before_action :set_homework_submission, only: [:show, :edit, :update, :destroy]

  # GET /homework_submissions
  # GET /homework_submissions.json
  def index
    @homework_submissions = HomeworkSubmission.find(params[:id])
  end


  # GET /homework_submissions/new
  def new
    @homework_id = params[:id]
    @homework_assignment_id = HomeworkAssignment.where("homework_id" => @homework_id).where("user_id"=>session[:user_id]).first.id
    @question = Homework.find(@homework_id).question
    @homework_submission = HomeworkSubmission.new
  end

  # GET /homework_submissions/1/edit
  def edit
  end

  # POST /homework_submissions
  # POST /homework_submissions.json
  def create
    homework_submission  = homework_submission_params
    homework_submission[:homework_submission][:user_id] = session[:user_id]

    @homework_submission = HomeworkSubmission.new(homework_submission_params)

    respond_to do |format|
      if @homework_submission.save
        format.html { redirect_to '/', notice: 'Homework submission was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # GET /homework_submissions
  # GET /homework_submissions.json
  def submissionsByUserForHomework
    homework_id = params[:homework_id]
    user_id = params[:user_id]

    @user = User.find(user_id)
    @homework = Homework.find(homework_id)
    # TODO - Better way to parametrize and avoid injection hole?
    @submissions = HomeworkSubmission.includes(:homework_assignment).joins("INNER JOIN homework_assignments ON homework_assignments.id = homework_submissions.homework_assignment_id AND homework_assignments.homework_id = " + HomeworkSubmission.sanitize(homework_id) + " AND homework_assignments.user_id = " + HomeworkSubmission.sanitize(user_id) + " ORDER BY homework_submissions.created_at DESC ")
  
    if (@submissions.blank?) 
      flash[:notice] = "Nothing to show...please check back later."
    end

  end

  def viewLatestForAssignment
    homework_id = params[:homework_id]
    @homework = Homework.find(homework_id)

    # TODO - injection hole - how do I parametrize this?
    @submissions = HomeworkSubmission.select("MAX(homework_submissions.created_at) as max_created_at, *").joins("INNER JOIN homework_assignments ON homework_assignments.id = homework_submissions.homework_assignment_id AND homework_assignments.homework_id = ", HomeworkSubmission.sanitize(homework_id),  "GROUP BY homework_assignment_id").includes(:homework_assignment =>  [:user])

    if (@submissions.blank?) 
      flash[:notice] = "Nothing to show...please check back later."
    end

  end

 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homework_submission
      @homework_submission = HomeworkSubmission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homework_submission_params
      params.require(:homework_submission).permit(:answer, :homework_assignment_id)
    end
end

app/helpers/homework_submissions_helper.rb
module HomeworkSubmissionsHelper
end

app/views/homework_submissions/_form.html.erb
<%= form_for(@homework_submission) do |f| %>
  <% if @homework_submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homework_submission.errors.count, "error") %> prohibited this homework_submission from being saved:</h2>

      <ul>
      <% @homework_submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homework_submissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Homework Submissions</h1>

<table class="table-bordered">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homework_submissions.each do |homework_submission| %>
      <tr>
        <td><%= link_to 'Show', homework_submission %></td>
        <td><%= link_to 'Edit', edit_homework_submission_path(homework_submission) %></td>
        <td><%= link_to 'Destroy', homework_submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homework submission', new_homework_submission_path %>

app/views/homework_submissions/new.html.erb
<h1>New Homework Submission</h1>

<h3><%= @question %></h3>	

<%= form_for @homework_submission, url: {action: "create"}, html: {class: "hw_form"} do |f| %>
	<%= f.hidden_field :homework_assignment_id,  :value => @homework_assignment_id %>
  <%= f.text_area :answer, size: "60x12" %>
  <%= f.submit "Create", :class => 'btn-primary' %>
<% end %>

app/views/homework_submissions/submissionsByUserForHomework.html.erb
<p id="notice"><%= notice %></p>

<h1>Homework submissions by <%= @user.username %> for <%= @homework.title %> </h1>
<h3>Question: <%= @homework.question %>

<table class="table-bordered">
  <thead>
    <tr>
      <th>Answer</th>
      <th>Answer Date</th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |homework_submission| %>
      <tr>
         <td><%= homework_submission.answer %></td>
         <td><%= homework_submission.created_at.strftime('%F, %H:%M') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/homework_submissions/viewLatestForAssignment.html.erb
<p id="notice"><%= notice %></p>

<h1>Latest submissions for homework "<%= @homework.title %>"</h1>
<h3>Question: <%= @homework.question %></h3>

<table class="table-bordered">
  <thead>
    <tr>
      <th>Answered on</th>
      <th>Answered By</th>
      <th>Answer</th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |homework_submission| %>
      <tr>
        <td><%= Date.parse(homework_submission.max_created_at).strftime('%F') %></td>
        <td><%= link_to homework_submission.homework_assignment.user.username, "/user/#{homework_submission.homework_assignment.user.id}/homework/#{@homework.id}" %></td>
        <td><%= homework_submission.answer %></td>
      </tr>
    <% end %>
  </tbody>
</table>