config/routes.rb
Rails.application.routes.draw do
  resources :homework_submissions
  resources :homework_assignments
  resources :homework_assignments
  resources :homeworks
  get 'homeworks/index'

  root 'homeworks#index'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create', as: 'session'
  match 'logout', to: 'sessions#destroy', as: 'logout', via: [:get, :delete]

    get 'assignments' => 'homework_assignments#index'
    get 'submit/:id' => 'homework_submissions#new'
    get 'user/:user_id/homework/:homework_id' => 'homework_submissions#submissionsByUserForHomework'
    get 'homework/:homework_id' => 'homework_submissions#viewLatestForAssignment'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homework</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller].parameterize %> <%= params[:action].parameterize %>" role="document">
<div class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Homework", root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li>
            <%= link_to "Logout, " + current_user.username, logout_url %>
          </li>          
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
<div class="container">
<%= yield %>


<div class="footer"><%= link_to 'Back to home', '/' %></div>

</div>

</body>
</html>